### ISSUE TITLE
the `available` field in MQTT

### ISSUE THREAD

**Issue by mario-tux** [mduran80/pymadoka#13]
I'm trying to use `pymadoka-mqtt` to manage my Dakin controllers from HA without the (pending) specific integration. I'm using the MQTT HVAC component with the following configuration:
```
mqtt:
  climate:
    - name: Daikin Studio Thermostat
      unique_id: daikin-studio
      availability:
        - topic: "madoka/daikin-studio/available"
          payload_available: "1"
          payload_not_available: "0"
      current_temperature_topic: "madoka/daikin-studio/state/get"
      current_temperature_template: "{{ value_json.temperatures['indoor'] }}"
      fan_modes:
        - "high"
        - "medium"
        - "low"
        - "auto"
      fan_mode_command_topic: "madoka/daikin-studio/fan_speed/set"
      fan_mode_command_template: "{% set values = { 'auto':'AUTO', 'low':'LOW', 'medium':'MID', 'high':'HIGH' } %}{{ values[value] }}"
      fan_mode_state_topic: "madoka/daikin-studio/state/get"
      fan_mode_state_template: "{% set values = { 'AUTO':'auto', 'LOW':'low', 'MEDIUM':'medium', 'HIGH':'high' } %} {{ values[value_json.fan_speed['heating_fan_speed']] if value_json.operation_mode['operation_mode']=='HEAT' else values[value_json.fan_speed['cooling_fan_speed']]}}"
      modes:
        - "auto"
        - "off"
        - "cool"
        - "heat"
        - "dry"
        - "fan_only"
      mode_command_topic: "madoka/daikin-studio/operation_mode/set"
      mode_command_template: "{% set values = { 'auto':'AUTO', 'heat':'HEAT', 'cool':'COOL', 'fan_only':'FAN', 'dry':'DRY', 'off':'OFF' } %}{{ values[value] if value in values.keys() else 'AUTO' }}"
      mode_state_topic: "madoka/daikin-studio/state/get"
      mode_state_template: "{% set values = { 'off':'off', 'HEAT':'heat', 'COOL':'cool', 'FAN':'fan_only', 'AUTO':'auto', 'DRY':'dry' } %} {{values[value_json.operation_mode['operation_mode']] if value_json.power_state['turn_on'] else 'off' }}"
      min_temp: 17
      max_temp: 31
      precision: 1
      temperature_state_topic: "madoka/daikin-studio/state/get"
      temperature_state_template: "{{ value_json.set_point['heating_set_point'] if value_json.operation_mode['operation_mode']=='HEAT' else value_json.set_point['cooling_set_point']}}"
      temperature_command_topic: "madoka/daikin-studio/set_point/set"
      temperature_command_template: "{{ int(value) }}"
      temperature_unit: "C"
      temp_step: 1
      device:
        manufacturer: "Daikin"
        via_device: "Madoka"
        name: "Daikin Madoka Remote Controller"
        model: "Madoka (BRC1H)"
        identifiers: "BRC1H"
```

I'm still tweaking this configuration but it works for 80% of the cases: there are issues with the double setpoints as reported in the README of the project. My configuration is a minor adjustment of the one published by @angeloniclaudio in https://github.com/mduran80/pymadoka/issues/12 : thanks to Claudio!

I'm opening this report because there is another issue with the MQTT `available` field: it looks that it is not "refreshed" by `pymadoka-mqtt` agent and HA considers it valid only if it is "fresh". 
Few experiments can clarify the behavior:
- if I launch HA and, later, `pymadoka-mqtt` then HA recognizes as available the thermostat;
- with a working HA thermostat, if i restart HA, on the new session HA will consider "unavailable" the thermostat until a restart of `pymadoka-mqtt`;
- if I remove the availability-related lines from the previous configuration, the thermostat is considered always working even if the `pymadoka-mqtt` agent is stopped.

As long as I understand, it looks that the `available` field should be "refreshed" as long as the `pymadoka-mqtt` agent keeps the connection with the physical thermostat.
